#!/bin/bash
# =============================================================================
# CONCILIO GENERAL DE EJÉRCITOS — Resumen del proyecto
# Generado: 2026-06-18
# =============================================================================

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║         CONCILIO GENERAL DE EJÉRCITOS — Estado del Proyecto         ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# -----------------------------------------------------------------------------
echo "── STACK ────────────────────────────────────────────────────────────────"
echo "  Framework:    Next.js 16.2.9 (App Router, TypeScript)"
echo "  Estilos:      TailwindCSS v4 — @theme en globals.css (sin tailwind.config.js)"
echo "  Base de datos: PostgreSQL 18 local → Prisma ORM v6"
echo "  Autenticación: NextAuth.js v5 (JWT, Credentials, 5 roles)"
echo "  Deploy target: Vercel"
echo ""

# -----------------------------------------------------------------------------
echo "── VARIABLES DE ENTORNO REQUERIDAS (.env) ───────────────────────────────"
echo "  DATABASE_URL=postgresql://postgres:PASS@localhost:5432/cge_db"
echo "  NEXTAUTH_SECRET=<string 32 chars>"
echo "  NEXTAUTH_URL=http://localhost:3000"
echo "  SEED_ADMIN_USERNAME=Mitsukai"
echo "  SEED_ADMIN_EMAIL=admin@cge.com"
echo "  SEED_ADMIN_PASSWORD=<contraseña>"
echo "  STORAGE_PROVIDER=none|vercel|cloudinary"
echo ""

# -----------------------------------------------------------------------------
echo "── COMANDOS ÚTILES ──────────────────────────────────────────────────────"
echo "  npm run dev          → Servidor de desarrollo (http://localhost:3000)"
echo "  npm run build        → Build de producción"
echo "  npx prisma studio    → Explorar la DB visualmente"
echo "  npx prisma db seed   → Cargar datos iniciales"
echo "  npx prisma migrate dev --name <nombre>  → Nueva migración"
echo ""

# -----------------------------------------------------------------------------
echo "── CREDENCIALES DE ACCESO (desarrollo) ──────────────────────────────────"
echo "  Usuario: Mitsukai"
echo "  Password: Admin1234!"
echo "  Rol:     ADMIN"
echo "  URL:     http://localhost:3000/login"
echo ""

# -----------------------------------------------------------------------------
echo "── FASES COMPLETADAS ────────────────────────────────────────────────────"
echo ""
echo "  ✅ FASE 1 — Fundación"
echo "     · Next.js 16.2.9 scaffolded desde cero"
echo "     · TailwindCSS v4 con @theme (NO tailwind.config.js)"
echo "     · globals.css con todos los design tokens del mockup HTML"
echo "     · Fuentes: Cinzel / Crimson Pro / Inter via next/font/google"
echo "     · Componentes UI: LogoCGE, GoldLine, Ornament, DeptBadge, StatCounter"
echo "     · Header (dropdowns, sesión condicional, avatar Habbo)"
echo "     · Footer (columnas, links, año dinámico)"
echo "     · Root layout (HTML + CSS vars runtime + SessionProvider + RadioProvider)"
echo "     · Layout grupo (public) para Header+Footer en rutas públicas"
echo ""
echo "  ✅ FASE 2 — Base de Datos + Prisma"
echo "     · Schema v2.0: User, Ejercito, Noticia, Evento, ActividadEjercito,"
echo "       Mediacion, Incidencia, PruebaIncidencia, ComentarioIncidencia,"
echo "       CanalChat, MensajeChat, CodigoInvitacion, RadioConfig, SiteConfig"
echo "     · Enums: Role, RolEjercito, Departamento, EstadoMediacion, EstadoIncidencia"
echo "     · .env.example documentado"
echo "     · lib/prisma.ts — singleton para hot reload"
echo "     · prisma/seed.ts — admin, 4 ejércitos, radioConfig, siteConfig, 3 canales"
echo "     · Migración inicial aplicada a PostgreSQL local (cge_db)"
echo ""
echo "  ✅ FASE 3 — Autenticación"
echo "     · NextAuth v5 con Credentials provider (username + bcryptjs)"
echo "     · JWT callbacks: id, username, role, ejercitoId"
echo "     · types/next-auth.d.ts — augmentación de Session y JWT"
echo "     · proxy.ts — protección de /dashboard/* (Next.js 16)"
echo "     · /login — formulario con link a /registro"
echo ""
echo "  ✅ FASE 4 — Rutas Públicas"
echo "     · /         → Portada (hero, stats animados, noticias, sidebar, misión)"
echo "     · /noticias → Feed paginado con filtro por departamento"
echo "     · /noticias/[slug] → Artículo con contenido Tiptap sanitizado"
echo "     · /ejercitos → Grid completo con descripciones"
echo "     · /ejercitos/[slug] → Ficha pública (banner, descripción rica, miembros)"
echo "     · /rankings → Tabla con medallería"
echo "     · /eventos / /eventos/[slug]"
echo "     · /mediacion → Formulario público de solicitud"
echo "     · API Routes públicas: noticias, ejercitos, eventos, mediaciones, rankings, radio, site-config"
echo ""
echo "  ✅ FASE 5 — Dashboards"
echo "     · DashboardLayout — sidebar con avatar Habbo completo, nav por query params"
echo "     · /dashboard/admin — 8 secciones: Resumen, Ejércitos, Usuarios, Actividades,"
echo "       Mediaciones, Invitaciones, Radio, Configuración del sitio"
echo "     · /dashboard/reportero — lista noticias, editor Tiptap, publicar/borradores"
echo "     · /dashboard/comandante — ficha ejército, miembros+roles, editor descripción"
echo "     · /dashboard/juez — casos pendientes/propios, editor de resolución"
echo "     · Sin tabs duplicados — sidebar es la única navegación"
echo "     · API protegidas: POST/PATCH/DELETE noticias, PATCH ejercitos, GET/PATCH usuarios,"
echo "       POST actividades, GET/PATCH mediaciones, PATCH radio, PATCH site-config"
echo ""
echo "  ✅ FASE 6 — Radio + SiteConfig en Runtime"
echo "     · layout.tsx fetchea RadioConfig + SiteConfig en paralelo"
echo "     · Colores de departamento inyectados como CSS vars en <html> (override runtime)"
echo "     · generateMetadata() dinámico desde SiteConfig"
echo "     · RadioProvider recibe config real desde DB"
echo "     · Fallback graceful si DB no está disponible"
echo ""
echo "  ✅ FASE 7 — Sistema de Invitaciones + Registro"
echo "     · CodigoInvitacion — códigos rastreables (CGE-FAM-XXXX)"
echo "     · /registro — formulario con validación visual del código en tiempo real"
echo "     · Si registroAbierto=false → solo con código (configurable desde admin)"
echo "     · Registro vincula usuario al ejército y al creador del código"
echo "     · InvitacionesPanel — reutilizable en Admin y Comandante"
echo "     · API: /api/invitaciones (GET/POST), /api/registro (POST)"
echo ""
echo "  ✅ FASE 8 — Chat con SSE (Server-Sent Events)"
echo "     · CanalChat + MensajeChat en Prisma"
echo "     · /chat — lista de canales accesibles"
echo "     · /chat/[canalId] — mensajes en tiempo real via SSE"
echo "     · Burbujas diferenciadas (propio/otros), color por rol"
echo "     · Mensajes fijados visibles arriba del canal"
echo "     · Indicador En vivo / Reconectando"
echo "     · Optimistic updates"
echo "     · Soft delete de mensajes"
echo "     · Canales iniciales: #general, #anuncios, #jueces (privado JUEZ/ADMIN)"
echo "     · API: /api/chat/canales, /api/chat/[canalId]/messages, /api/chat/[canalId]/stream,"
echo "       /api/chat/messages/[id]"
echo "     ⚠ NOTA: SSE in-memory funciona en local. En Vercel Serverless migrar a Supabase Realtime"
echo ""
echo "  ✅ FASE 9 — Incidencias (Sistema Judicial)"
echo "     · EstadoIncidencia: ABIERTA → EN_REVISION → EN_PROCESO → RESUELTA/DESESTIMADA"
echo "     · Privacidad real a nivel de query: denunciado no ve la incidencia hasta EN_PROCESO"
echo "     · COMANDANTE, OFICIAL, EMBAJADOR pueden crear incidencias"
echo "     · JUEZ y ADMIN gestionan, comentan internamente, resuelven"
echo "     · Pruebas: URL, imagen, texto"
echo "     · Al resolver → genera noticia automática en Juzgado"
echo "     · /incidencias — página autenticada (lista/nueva/detalle en una sola página)"
echo "     · AdminIncidencias — sección en dashboard admin"
echo "     · API: /api/incidencias (GET/POST), /api/incidencias/[id] (GET/PATCH),"
echo "       /api/incidencias/[id]/pruebas, /api/incidencias/[id]/comentarios"
echo ""

# -----------------------------------------------------------------------------
echo "── AVATARES HABBO ───────────────────────────────────────────────────────"
echo "  Cabeza (menú):  https://www.habbo.es/habbo-imaging/avatarimage?user={name}&size=l&direction=1&head_direction=2&gesture=sml&headonly=1"
echo "  Completo (sidebar): https://www.habbo.es/habbo-imaging/avatarimage?user={name}&size=l&direction=2&head_direction=2&action=wlk,wav&gesture=sml&headonly=0"
echo "  Helper: lib/habbo.ts → habboAvatarHead(username) / habboAvatarFull(username)"
echo ""

# -----------------------------------------------------------------------------
echo "── ARQUITECTURA DE LAYOUTS ──────────────────────────────────────────────"
echo "  app/layout.tsx           → <html> + <body suppressHydrationWarning>"
echo "                              + SessionProvider + RadioProvider"
echo "                              (SIN Header/Footer)"
echo "  app/(public)/layout.tsx  → Header + Footer (todas las rutas públicas)"
echo "  app/dashboard/layout.tsx → DashboardLayout sidebar (sin Header/Footer del sitio)"
echo ""

# -----------------------------------------------------------------------------
echo "── RUTAS (40 total) ─────────────────────────────────────────────────────"
echo "  Públicas: / /noticias /noticias/[slug] /ejercitos /ejercitos/[slug]"
echo "            /eventos /eventos/[slug] /rankings /mediacion"
echo "  Auth:     /chat /chat/[canalId] /incidencias /login /registro"
echo "  Dashboard: /dashboard /dashboard/admin /dashboard/reportero"
echo "             /dashboard/comandante /dashboard/comandante/invitaciones"
echo "             /dashboard/juez"
echo "  API:      /api/auth /api/noticias /api/ejercitos /api/eventos"
echo "            /api/mediaciones /api/rankings /api/radio /api/site-config"
echo "            /api/usuarios /api/actividades /api/invitaciones /api/registro"
echo "            /api/incidencias /api/chat/..."
echo ""

# -----------------------------------------------------------------------------
echo "── PENDIENTE ────────────────────────────────────────────────────────────"
echo "  ✅ Gestión de canales de chat en dashboard Admin"
echo "  ✅ Radio: djAvatarUrl como nombre de Habbo (mostrar avatar dinámico)"
echo "  ✅ Subida de imágenes (Endpoint local con compresión sharp)"
echo "  ✅ ISR en producción: cambiar force-dynamic por revalidate=60"
echo "  ✅ SSE en producción: Mantener en memoria para VPS local"
echo "  ✅ Prisma config: Eliminado warning de package.json y cambiado a tsx"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "  Proyecto listo para desarrollo. Arrancá con: npm run dev"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
